-- Create contacts table
CREATE TABLE public.contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    email text,
    company text,
    role text
);

-- Create deals table
CREATE TABLE public.deals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    amount numeric,
    status text, -- 'active', 'won', 'lost'
    closed_at timestamp with time zone
);

-- Create table for dashboard charts (simplified for demo)
CREATE TABLE public.dashboard_chart_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month text,
    value numeric
);

CREATE TABLE public.dashboard_bar_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quarter text,
    deals_count integer,
    revenue numeric
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_chart_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_bar_data ENABLE ROW LEVEL SECURITY;

-- Create policies (public access for demo purposes, restricted in prod)
CREATE POLICY "Allow public read access" ON public.contacts FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.deals FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.dashboard_chart_data FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON public.dashboard_bar_data FOR SELECT USING (true);
